package companyinfo.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-05-17T20:40:35.237+02:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://example.companyInfo", name = "CompanyInfo")
@XmlSeeAlso({ObjectFactory.class, header.example.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CompanyInfo {

    @WebMethod(operationName = "GetCompanyInfo")
    public void getCompanyInfo(
        @WebParam(partName = "part1", name = "getCompanyInfo", targetNamespace = "http://example.companyInfo")
        GetCompanyInfo part1,
        @WebParam(partName = "part2", mode = WebParam.Mode.OUT, name = "getCompanyInfoResult", targetNamespace = "http://example.companyInfo")
        javax.xml.ws.Holder<GetCompanyInfoResult> part2,
        @WebParam(partName = "part3", mode = WebParam.Mode.OUT, name = "part3", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> part3,
        @WebParam(partName = "part4", mode = WebParam.Mode.OUT, name = "part4", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> part4
    );
}
