
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package demo.spring.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-05-17T09:15:27.544+02:00
 * Generated source version: 3.1.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldImplService",
                      portName = "HelloWorldImplPort",
                      targetNamespace = "http://service.spring.demo/",
                      wsdlLocation = "file:/C:/wsdl/HelloWorlds.wsdl",
                      endpointInterface = "demo.spring.service.HelloWorld")
                      
public class HelloWorldImplPortImpl implements HelloWorld {

    private static final Logger LOG = Logger.getLogger(HelloWorldImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see demo.spring.service.HelloWorld#sayHi(java.lang.String  arg0 )*
     */
    public java.lang.String sayHi(java.lang.String arg0) { 
        LOG.info("Executing operation sayHi");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
